temperature:
  key: "temperature"
  first_value: 27.5
  min_value: 27.0
  max_value: 29.0
  min_steps_trend: 1
  max_steps_trend: 100
humidity:
  key: "humidity"
  first_value: 40
  min_value: 35
  max_value: 60
  min_steps_trend: 50
  max_steps_trend: 200
pn:
  key: "pn"
  first_value: 10000
  min_value: 1000
  max_value: 100000
  min_steps_trend: 1
  max_steps_trend: 20
co:
  key: "co"
  first_value: 3.5
  min_value: 3
  max_value: 5
co2:
  key: "co2"
  first_value: 420
  min_value: 400
  max_value: 500
pm1:
  key: "pm1"
  first_value: 20
  min_value: 0
  max_value: 100
  min_steps_trend: 1
  max_steps_trend: 20
pm2_5:
  key: "pm2_5"
  first_value: 20
  min_value: 0
  max_value: 100
  min_steps_trend: 1
  max_steps_trend: 25
pm10:
  key: "pm10"
  first_value: 20
  min_value: 0
  max_value: 100
  min_steps_trend: 1
  max_steps_trend: 30
# ...
test0:
  key: "test0"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test1:
  key: "test1"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test2:
  key: "test2"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test3:
  key: "test3"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test4:
  key: "test4"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test5:
  key: "test5"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test6:
  key: "test6"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test7:
  key: "test7"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test8:
  key: "test8"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0
test9:
  key: "test9"
  first_value: 0
  min_value: 0
  max_value: 0
  min_steps_trend: 0
  max_steps_trend: 0